name: Execução Diária do Robô

on:
  schedule:
    - cron: '0 10 * * *'
  worflow_dispatch:

jobs:
  executar:
    runs-on: ubuntu-latest

    steps:
    - name : clonar repositório
      uses : actions/checkout@v3
      
    - name: Commit do relatório
      run: |
        git config user.name "github-actions"
        git add dados/relatorio.csv
        git commit -m "Atualização diária"
        git push
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
